version: '3.7'
services:
  postgres:
    container_name: postgres-super-cards
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: super_cards
    ports:
      - "5433:5432"
    volumes:
      - super-cards-volume:/applis/docker-compose/super_cards/data
volumes:
  super-cards-volume:
    external: true